package com.imiku.blog.dao;

import com.imiku.blog.model.BlogInfo;

public interface BlogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    int deleteByPrimaryKey(String blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    int insert(BlogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    int insertSelective(BlogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    BlogInfo selectByPrimaryKey(String blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    int updateByPrimaryKeySelective(BlogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_info
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    int updateByPrimaryKey(BlogInfo record);
}