package com.imiku.blog.dao;

import com.imiku.blog.model.CommentInfo;

public interface CommentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    int insert(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    int insertSelective(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    CommentInfo selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    int updateByPrimaryKeySelective(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CommentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    int updateByPrimaryKey(CommentInfo record);
}