package com.imiku.blog.dao;

import com.imiku.blog.model.PageView;

public interface PageViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    int deleteByPrimaryKey(Integer pageViewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    int insert(PageView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    int insertSelective(PageView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    PageView selectByPrimaryKey(Integer pageViewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    int updateByPrimaryKeySelective(PageView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    int updateByPrimaryKey(PageView record);
}