package com.imiku.blog.dao;

import com.imiku.blog.model.RoleInfo;

import java.util.List;

public interface RoleInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    int insert(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    int insertSelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    RoleInfo selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    int updateByPrimaryKeySelective(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_info
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    int updateByPrimaryKey(RoleInfo record);

    List<RoleInfo> findRoleByUserId(int userId);
}