package com.imiku.blog.dao;

import com.imiku.blog.model.RoleResourceKey;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Tue Mar 28 00:19:53 CST 2017
     */
    int deleteByPrimaryKey(RoleResourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Tue Mar 28 00:19:53 CST 2017
     */
    int insert(RoleResourceKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Tue Mar 28 00:19:53 CST 2017
     */
    int insertSelective(RoleResourceKey record);
}