package com.imiku.blog.dao;

import com.imiku.blog.model.TypeInfo;

import java.util.List;

public interface TypeInfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Tue Mar 28 00:20:04 CST 2017
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Tue Mar 28 00:20:04 CST 2017
     */
    int insert(TypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Tue Mar 28 00:20:04 CST 2017
     */
    int insertSelective(TypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Tue Mar 28 00:20:04 CST 2017
     */
    TypeInfo selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Tue Mar 28 00:20:04 CST 2017
     */
    int updateByPrimaryKeySelective(TypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbggenerated Tue Mar 28 00:20:04 CST 2017
     */
    int updateByPrimaryKey(TypeInfo record);

    List<TypeInfo> findAllTypes();
}