package com.imiku.blog.model;

import java.util.Date;

public class BlogInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.blog_id
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    private String blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.blog_title
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    private String blogTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.blog_abstract
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    private String blogAbstract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.blog_author
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    private String blogAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.create_date
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.type_id
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.lable_name
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    private String lableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.blog_url
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    private String blogUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_info.blog_cover
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    private String blogCover;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.blog_id
     *
     * @return the value of blog_info.blog_id
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public String getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.blog_id
     *
     * @param blogId the value for blog_info.blog_id
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public void setBlogId(String blogId) {
        this.blogId = blogId == null ? null : blogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.blog_title
     *
     * @return the value of blog_info.blog_title
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.blog_title
     *
     * @param blogTitle the value for blog_info.blog_title
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.blog_abstract
     *
     * @return the value of blog_info.blog_abstract
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public String getBlogAbstract() {
        return blogAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.blog_abstract
     *
     * @param blogAbstract the value for blog_info.blog_abstract
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public void setBlogAbstract(String blogAbstract) {
        this.blogAbstract = blogAbstract == null ? null : blogAbstract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.blog_author
     *
     * @return the value of blog_info.blog_author
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public String getBlogAuthor() {
        return blogAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.blog_author
     *
     * @param blogAuthor the value for blog_info.blog_author
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public void setBlogAuthor(String blogAuthor) {
        this.blogAuthor = blogAuthor == null ? null : blogAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.create_date
     *
     * @return the value of blog_info.create_date
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.create_date
     *
     * @param createDate the value for blog_info.create_date
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.type_id
     *
     * @return the value of blog_info.type_id
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.type_id
     *
     * @param typeId the value for blog_info.type_id
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.lable_name
     *
     * @return the value of blog_info.lable_name
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public String getLableName() {
        return lableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.lable_name
     *
     * @param lableName the value for blog_info.lable_name
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public void setLableName(String lableName) {
        this.lableName = lableName == null ? null : lableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.blog_url
     *
     * @return the value of blog_info.blog_url
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public String getBlogUrl() {
        return blogUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.blog_url
     *
     * @param blogUrl the value for blog_info.blog_url
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public void setBlogUrl(String blogUrl) {
        this.blogUrl = blogUrl == null ? null : blogUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_info.blog_cover
     *
     * @return the value of blog_info.blog_cover
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public String getBlogCover() {
        return blogCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_info.blog_cover
     *
     * @param blogCover the value for blog_info.blog_cover
     *
     * @mbggenerated Tue Mar 28 00:20:45 CST 2017
     */
    public void setBlogCover(String blogCover) {
        this.blogCover = blogCover == null ? null : blogCover.trim();
    }
}