package com.imiku.blog.model;

import java.util.Date;

public class CommentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_info.comment_id
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_info.user_id
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_info.create_date
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_info.blog_id
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    private String blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_info.comment_text
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    private String commentText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.comment_id
     *
     * @return the value of comment_info.comment_id
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.comment_id
     *
     * @param commentId the value for comment_info.comment_id
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.user_id
     *
     * @return the value of comment_info.user_id
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.user_id
     *
     * @param userId the value for comment_info.user_id
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.create_date
     *
     * @return the value of comment_info.create_date
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.create_date
     *
     * @param createDate the value for comment_info.create_date
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.blog_id
     *
     * @return the value of comment_info.blog_id
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    public String getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.blog_id
     *
     * @param blogId the value for comment_info.blog_id
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    public void setBlogId(String blogId) {
        this.blogId = blogId == null ? null : blogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_info.comment_text
     *
     * @return the value of comment_info.comment_text
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    public String getCommentText() {
        return commentText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_info.comment_text
     *
     * @param commentText the value for comment_info.comment_text
     *
     * @mbggenerated Tue Mar 28 00:21:07 CST 2017
     */
    public void setCommentText(String commentText) {
        this.commentText = commentText == null ? null : commentText.trim();
    }
}