package com.imiku.blog.model;

import java.util.Date;

public class JournalInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal_info.journal_id
     *
     * @mbggenerated Wed Apr 19 14:54:45 CST 2017
     */
    private Integer journalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal_info.journal_context
     *
     * @mbggenerated Wed Apr 19 14:54:45 CST 2017
     */
    private String journalContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journal_info.create_date
     *
     * @mbggenerated Wed Apr 19 14:54:45 CST 2017
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal_info.journal_id
     *
     * @return the value of journal_info.journal_id
     *
     * @mbggenerated Wed Apr 19 14:54:45 CST 2017
     */
    public Integer getJournalId() {
        return journalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal_info.journal_id
     *
     * @param journalId the value for journal_info.journal_id
     *
     * @mbggenerated Wed Apr 19 14:54:45 CST 2017
     */
    public void setJournalId(Integer journalId) {
        this.journalId = journalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal_info.journal_context
     *
     * @return the value of journal_info.journal_context
     *
     * @mbggenerated Wed Apr 19 14:54:45 CST 2017
     */
    public String getJournalContext() {
        return journalContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal_info.journal_context
     *
     * @param journalContext the value for journal_info.journal_context
     *
     * @mbggenerated Wed Apr 19 14:54:45 CST 2017
     */
    public void setJournalContext(String journalContext) {
        this.journalContext = journalContext == null ? null : journalContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journal_info.create_date
     *
     * @return the value of journal_info.create_date
     *
     * @mbggenerated Wed Apr 19 14:54:45 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journal_info.create_date
     *
     * @param createDate the value for journal_info.create_date
     *
     * @mbggenerated Wed Apr 19 14:54:45 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}