package com.imiku.blog.model;

import java.util.Date;

public class NoticeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_info.notice_id
     *
     * @mbggenerated Wed Apr 19 14:55:00 CST 2017
     */
    private Integer noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_info.notice_context
     *
     * @mbggenerated Wed Apr 19 14:55:00 CST 2017
     */
    private String noticeContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_info.create_date
     *
     * @mbggenerated Wed Apr 19 14:55:00 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_info.level
     *
     * @mbggenerated Wed Apr 19 14:55:00 CST 2017
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_info.notice_id
     *
     * @return the value of notice_info.notice_id
     *
     * @mbggenerated Wed Apr 19 14:55:00 CST 2017
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_info.notice_id
     *
     * @param noticeId the value for notice_info.notice_id
     *
     * @mbggenerated Wed Apr 19 14:55:00 CST 2017
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_info.notice_context
     *
     * @return the value of notice_info.notice_context
     *
     * @mbggenerated Wed Apr 19 14:55:00 CST 2017
     */
    public String getNoticeContext() {
        return noticeContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_info.notice_context
     *
     * @param noticeContext the value for notice_info.notice_context
     *
     * @mbggenerated Wed Apr 19 14:55:00 CST 2017
     */
    public void setNoticeContext(String noticeContext) {
        this.noticeContext = noticeContext == null ? null : noticeContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_info.create_date
     *
     * @return the value of notice_info.create_date
     *
     * @mbggenerated Wed Apr 19 14:55:00 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_info.create_date
     *
     * @param createDate the value for notice_info.create_date
     *
     * @mbggenerated Wed Apr 19 14:55:00 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_info.level
     *
     * @return the value of notice_info.level
     *
     * @mbggenerated Wed Apr 19 14:55:00 CST 2017
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_info.level
     *
     * @param level the value for notice_info.level
     *
     * @mbggenerated Wed Apr 19 14:55:00 CST 2017
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }
}