package com.imiku.blog.model;

import java.util.Date;

public class PageView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_view.page_view_id
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    private Integer pageViewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_view.blog_id
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    private String blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_view.page_view_date
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    private Date pageViewDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_view.view_ip
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    private String viewIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_view.page_view_id
     *
     * @return the value of page_view.page_view_id
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    public Integer getPageViewId() {
        return pageViewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_view.page_view_id
     *
     * @param pageViewId the value for page_view.page_view_id
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    public void setPageViewId(Integer pageViewId) {
        this.pageViewId = pageViewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_view.blog_id
     *
     * @return the value of page_view.blog_id
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    public String getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_view.blog_id
     *
     * @param blogId the value for page_view.blog_id
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    public void setBlogId(String blogId) {
        this.blogId = blogId == null ? null : blogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_view.page_view_date
     *
     * @return the value of page_view.page_view_date
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    public Date getPageViewDate() {
        return pageViewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_view.page_view_date
     *
     * @param pageViewDate the value for page_view.page_view_date
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    public void setPageViewDate(Date pageViewDate) {
        this.pageViewDate = pageViewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_view.view_ip
     *
     * @return the value of page_view.view_ip
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    public String getViewIp() {
        return viewIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_view.view_ip
     *
     * @param viewIp the value for page_view.view_ip
     *
     * @mbggenerated Tue Mar 28 00:19:19 CST 2017
     */
    public void setViewIp(String viewIp) {
        this.viewIp = viewIp == null ? null : viewIp.trim();
    }
}