package com.imiku.blog.model;

public class ResourcesInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_info.resources_id
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    private Integer resourcesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_info.resources_name
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    private String resourcesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_info.parent_id
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_info.res_key
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    private String resKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_info.type
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_info.res_url
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    private String resUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_info.level
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_info.icon
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_info.is_hide
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    private Integer isHide;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resources_info.description
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_info.resources_id
     *
     * @return the value of resources_info.resources_id
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public Integer getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_info.resources_id
     *
     * @param resourcesId the value for resources_info.resources_id
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public void setResourcesId(Integer resourcesId) {
        this.resourcesId = resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_info.resources_name
     *
     * @return the value of resources_info.resources_name
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public String getResourcesName() {
        return resourcesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_info.resources_name
     *
     * @param resourcesName the value for resources_info.resources_name
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public void setResourcesName(String resourcesName) {
        this.resourcesName = resourcesName == null ? null : resourcesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_info.parent_id
     *
     * @return the value of resources_info.parent_id
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_info.parent_id
     *
     * @param parentId the value for resources_info.parent_id
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_info.res_key
     *
     * @return the value of resources_info.res_key
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public String getResKey() {
        return resKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_info.res_key
     *
     * @param resKey the value for resources_info.res_key
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public void setResKey(String resKey) {
        this.resKey = resKey == null ? null : resKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_info.type
     *
     * @return the value of resources_info.type
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_info.type
     *
     * @param type the value for resources_info.type
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_info.res_url
     *
     * @return the value of resources_info.res_url
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public String getResUrl() {
        return resUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_info.res_url
     *
     * @param resUrl the value for resources_info.res_url
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public void setResUrl(String resUrl) {
        this.resUrl = resUrl == null ? null : resUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_info.level
     *
     * @return the value of resources_info.level
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_info.level
     *
     * @param level the value for resources_info.level
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_info.icon
     *
     * @return the value of resources_info.icon
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_info.icon
     *
     * @param icon the value for resources_info.icon
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_info.is_hide
     *
     * @return the value of resources_info.is_hide
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public Integer getIsHide() {
        return isHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_info.is_hide
     *
     * @param isHide the value for resources_info.is_hide
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public void setIsHide(Integer isHide) {
        this.isHide = isHide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resources_info.description
     *
     * @return the value of resources_info.description
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resources_info.description
     *
     * @param description the value for resources_info.description
     *
     * @mbggenerated Tue Mar 28 00:19:28 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}