package com.imiku.blog.model;

public class RoleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.role_id
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.state
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.role_name
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.role_key
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    private String roleKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_info.description
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.role_id
     *
     * @return the value of role_info.role_id
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.role_id
     *
     * @param roleId the value for role_info.role_id
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.state
     *
     * @return the value of role_info.state
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.state
     *
     * @param state the value for role_info.state
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.role_name
     *
     * @return the value of role_info.role_name
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.role_name
     *
     * @param roleName the value for role_info.role_name
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.role_key
     *
     * @return the value of role_info.role_key
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    public String getRoleKey() {
        return roleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.role_key
     *
     * @param roleKey the value for role_info.role_key
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    public void setRoleKey(String roleKey) {
        this.roleKey = roleKey == null ? null : roleKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_info.description
     *
     * @return the value of role_info.description
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_info.description
     *
     * @param description the value for role_info.description
     *
     * @mbggenerated Tue Mar 28 00:19:38 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}