package com.imiku.blog.model;

public class RoleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.role_resource_id
     *
     * @mbggenerated Thu Mar 30 15:41:14 CST 2017
     */
    private Integer roleResourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.role_id
     *
     * @mbggenerated Thu Mar 30 15:41:14 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_resource.resource_id
     *
     * @mbggenerated Thu Mar 30 15:41:14 CST 2017
     */
    private Integer resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.role_resource_id
     *
     * @return the value of role_resource.role_resource_id
     *
     * @mbggenerated Thu Mar 30 15:41:14 CST 2017
     */
    public Integer getRoleResourceId() {
        return roleResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.role_resource_id
     *
     * @param roleResourceId the value for role_resource.role_resource_id
     *
     * @mbggenerated Thu Mar 30 15:41:14 CST 2017
     */
    public void setRoleResourceId(Integer roleResourceId) {
        this.roleResourceId = roleResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.role_id
     *
     * @return the value of role_resource.role_id
     *
     * @mbggenerated Thu Mar 30 15:41:14 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.role_id
     *
     * @param roleId the value for role_resource.role_id
     *
     * @mbggenerated Thu Mar 30 15:41:14 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_resource.resource_id
     *
     * @return the value of role_resource.resource_id
     *
     * @mbggenerated Thu Mar 30 15:41:14 CST 2017
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_resource.resource_id
     *
     * @param resourceId the value for role_resource.resource_id
     *
     * @mbggenerated Thu Mar 30 15:41:14 CST 2017
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }
}