package com.imiku.blog.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.account_name
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.credentials_salt
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    private String credentialsSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.description
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.locked
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    private String locked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_date
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.delete_status
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    private Integer deleteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.account_name
     *
     * @return the value of user_info.account_name
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.account_name
     *
     * @param accountName the value for user_info.account_name
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.credentials_salt
     *
     * @return the value of user_info.credentials_salt
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public String getCredentialsSalt() {
        return credentialsSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.credentials_salt
     *
     * @param credentialsSalt the value for user_info.credentials_salt
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public void setCredentialsSalt(String credentialsSalt) {
        this.credentialsSalt = credentialsSalt == null ? null : credentialsSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.description
     *
     * @return the value of user_info.description
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.description
     *
     * @param description the value for user_info.description
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.locked
     *
     * @return the value of user_info.locked
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public String getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.locked
     *
     * @param locked the value for user_info.locked
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public void setLocked(String locked) {
        this.locked = locked == null ? null : locked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_date
     *
     * @return the value of user_info.create_date
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_date
     *
     * @param createDate the value for user_info.create_date
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.delete_status
     *
     * @return the value of user_info.delete_status
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.delete_status
     *
     * @param deleteStatus the value for user_info.delete_status
     *
     * @mbggenerated Tue Mar 28 00:20:17 CST 2017
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }
}